-- Source: deterministic match from star_schema_pipeline (adapted: 4 sources collapsed to 2, 3 INNER JOINs removed, COALESCE logic eliminated)
WITH
metrics_joined AS (
  SELECT
    TRIM(om.STUDY_NUMBER) AS STUDY_ID,
    TRIM(CRITICAL_PATH_IND) AS BSC_CRITICALPATH_STUDY,
    TRIM(CONTACT_PROVIDER) AS CONTACT_CARD_PROVIDER,
    CAST(CPOC_PERCENT_COMPLETE AS DOUBLE) AS CPOC_COMPLETION_PERCENTAGE,
    TRIM(IQMP_FULL_FLAG) AS FULL_IQMP_REQUIRED,
    TRIM(GLOBAL_PLACEMENT) AS GLOBAL_TRIAL_PLACEMENT,
    CAST(MONITOR_INTERVAL_MAX AS BIGINT) AS MONITOR_VISIT_PLAN_INTERVAL_MAX,
    TRIM(PIMS_INDICATOR) AS PIMS_FLG,
    TRIM(RAP_RCPMS_IND) AS RAP_RCPMS_FLAG,
    TRIM(RCPMS_INDICATOR) AS RCPMS_FLAG,
    TRIM(RECRUITMENT_COUNTRY_LIST) AS RECRUITMENT_COUNTRY,
    TRIM(RECRUITMENT_DESIGN) AS RECRUITMENT_DESIGN_TYPE,
    TRIM(RECRUITMENT_VERSION) AS RECRUITMENT_DESIGN_VERSION,
    TRIM(RECRUITMENT_APPROACH) AS RECRUITMENT_METHOD,
    CAST(RECRUITMENT_BEGIN_DATE AS DATE) AS RECRUITMENT_START_DATE,
    TRIM(RFSSMI_INDICATOR) AS RFSSMI_FLAG,
    TRIM(TMF_REQUIRED) AS TMF_REQUIREMENT_FLAG,
    TRIM(ADJUDICATION_COMMITTEE) AS COMMITTEE_ADJUDICATION_USED,
    TRIM(DMC_FLAG) AS COMMITTEE_DMC_USED,
    CAST(NULL AS VARCHAR) AS COMMITTEE_NONE_USED,
    CASE
      WHEN APPROVED_PRODUCT_EU = TRUE THEN 'Y'
      WHEN APPROVED_PRODUCT_EU = FALSE THEN 'N'
      ELSE NULL
    END AS EU_APPROVED_PRODUCT,
    CAST(IB_REVISION_DATE AS TIMESTAMP) AS IB_VERSION_DT,
    CASE
      WHEN PAPER_CRF_USED = TRUE THEN 'Y'
      WHEN PAPER_CRF_USED = FALSE THEN 'N'
      ELSE NULL
    END AS PAPER_STUDY,
    TRIM(EDC_SYSTEM) AS PATIENT_DATABASE,
    TRIM(SUBJECT_TYPE) AS SUBJECTS_RECRUITED_TYPE,
    CAST(COMPLETION_TARGET AS BIGINT) AS TARGET_COMPLETE_NUMBER,
    CAST(ENROLLMENT_TARGET AS BIGINT) AS PLANNED_PATIENTS,
    CAST(NULL AS VARCHAR) AS PLANNED_PATIENTS_SOURCE,
    TRIM(DATA_COLLECTION_PRIMARY) AS PRIMARY_DATA_COLLECTION,
    TRIM(DATA_COLLECTION_SECONDARY) AS SECONDARY_DATA_COLLECTION,
    TRIM(DATA_RETURN_COMPLETE) AS DATA_RETURN_PLAN_COMPLETE_FLAG,
    TRIM(DATA_WITHHELD_FLAG) AS PARTICIPANT_DATA_WITHHELD_UNTIL_LSLV_FLAG,
    TRIM(PARTICIPANT_RETURN_ELIGIBLE) AS PARTICIPANT_ELIGIBLE_TO_RETURN_FLAG,
    TRIM(STUDY_RATIONALE) AS BUSINESS_RATIONALE,
    TRIM(MEDICAL_OWNER) AS MEDICAL_RESPONSIBILITY,
    TRIM(PROJECT_TYPE) AS PROJECT_PLAN_TYPE,
    CAST(SAP_END AS TIMESTAMP) AS SAP_FINISH_DATE,
    CAST(SAP_COMPLETION_PCT AS BIGINT) AS SAP_PCT_COMPLETED,
    CAST(SAP_START AS TIMESTAMP) AS SAP_START_DATE,
    TRIM(CLINICAL_PM) AS STUDY_CPM,
    TRIM(EXECUTION_STATUS) AS STUDY_EXECUTION_STATE,
    TRIM(PERFORMING_SITE) AS STUDY_PERFORMING_SITE,
    TRIM(PROJECT_NAME) AS STUDY_PROJECT_PLAN_NAME,
    TRIM(PROJECT_TEMPLATE) AS STUDY_PROJECT_PLAN_TEMPLATE_NAME,
    TRIM(PLAN_STATUS) AS STUDY_STATUS_PLAN,
    TRIM(PORTFOLIO_GROUP) AS BUSINESS_GROUP,
    TRIM(CLINICAL_PLACEMENT) AS CCS_CLINICAL_PLACEMENT,
    CAST('N' AS VARCHAR) AS DELETE_FLAG,
    CAST(CREATE_TIMESTAMP AS TIMESTAMP) AS START_DT,
    CAST(UPDATE_TIMESTAMP AS TIMESTAMP) AS END_DT,
    CAST(LAST_MODIFIED AS TIMESTAMP) AS LOAD_DATE
  FROM operational_metrics AS om
  LEFT JOIN trial_master AS tm ON TRIM(om.STUDY_NUMBER) = TRIM(tm.TRIAL_NUMBER)
),

final_output AS (
  SELECT * FROM metrics_joined
)

SELECT * FROM final_output
