WITH
dsopi_transformed AS (
  SELECT
    TRIM(STUDY_ID) AS STUDY_ID,
    TRIM(BSC_CRITICAL_PATH_STUDY_FLG) AS BSC_CRITICALPATH_STUDY,
    TRIM(COMMI_ADJUDICATION_USED) AS COMMITTEE_ADJUDICATION_USED,
    TRIM(COMMI_DMC_USED) AS COMMITTEE_DMC_USED,
    TRIM(COMMI_NONE_USED) AS COMMITTEE_NONE_USED,
    TRIM(CONTACT_CARD_PROVIDER) AS CONTACT_CARD_PROVIDER,
    CPOC_COMPLETION_PERCNTG AS CPOC_COMPLETION_PERCENTAGE,
    TRIM(EU_APPROVED_PRODUCT) AS EU_APPROVED_PRODUCT,
    TRIM(IQMP_REQUIREMENT_FLAG) AS FULL_IQMP_REQUIRED,
    TRIM(GLOBAL_TRIAL_PLACEMENT) AS GLOBAL_TRIAL_PLACEMENT,
    IB_VERSION_DATE AS IB_VERSION_DT,
    PMV_MAX_INTERVAL AS MONITOR_VISIT_PLAN_INTERVAL_MAX,
    TRIM(PAPER_STUDY_FLG) AS PAPER_STUDY,
    TRIM(PATIENT_DATABASE) AS PATIENT_DATABASE,
    TRIM(PIMS_FLG) AS PIMS_FLG,
    TOT_SUBJ_PLANNED_STUDY AS PLANNED_PATIENTS_DSOPI,
    TRIM(RAP_RCPMS_FLG) AS RAP_RCPMS_FLAG,
    TRIM(RCPMS_FLAG) AS RCPMS_FLAG,
    TRIM(RECRUITMENT_COUNTRY) AS RECRUITMENT_COUNTRY,
    TRIM(RECRUITMENT_DESIGN_TYPE) AS RECRUITMENT_DESIGN_TYPE,
    TRIM(RECRUITMENT_DESIGN_VERSION) AS RECRUITMENT_DESIGN_VERSION,
    TRIM(RECRUITMENT_METHOD) AS RECRUITMENT_METHOD,
    RECRUITMENT_START_DATE,
    TRIM(RFSSMI_FLAG) AS RFSSMI_FLAG,
    SUBJECTS_RECRUITED_TYPE,
    SUBJ_TARGET_COMPLETERS_NUM AS TARGET_COMPLETE_NUMBER,
    TRIM(TMF_REQUIREMENT_FLG) AS TMF_REQUIREMENT_FLAG,
    TRIM(DELETE_FLAG) AS DELETE_FLAG_DSOPI
  FROM dsopi_st_cln_study_operational
),

srt_transformed AS (
  SELECT
    TRIM(STUDY_ID) AS STUDY_ID,
    TRIM(COMMITTEE_ADJUDICATION_USED) AS COMMITTEE_ADJUDICATION_USED,
    TRIM(COMMITTEE_DMC_USED) AS COMMITTEE_DMC_USED,
    TRIM(COMMITTEE_NONE_USED) AS COMMITTEE_NONE_USED,
    TRIM(EU_APPROVED_PRODUCT) AS EU_APPROVED_PRODUCT,
    IB_VERSION_DT,
    TRIM(PAPER_STUDY) AS PAPER_STUDY,
    TRIM(PATIENT_DATABASE) AS PATIENT_DATABASE,
    TOT_SUBJ_PLANNED_STUDY AS PLANNED_PATIENTS_SRT,
    TRIM(PRIMARY_DATA_COLLECTION) AS PRIMARY_DATA_COLLECTION,
    TRIM(SECONDARY_DATA_COLLECTION) AS SECONDARY_DATA_COLLECTION,
    TRIM(SUBJECTS_RECRUITED_TYPE) AS SUBJECTS_RECRUITED_TYPE,
    SUBJ_TARGET_COMPLETERS_NUM AS TARGET_COMPLETE_NUMBER,
    TRIM(DATA_RETURN_PLAN_COMPLETE_FLAG) AS DATA_RETURN_PLAN_COMPLETE_FLAG,
    TRIM(PARTICIPANT_DATA_WITHHELD_UNTIL_LSLV_FLAG) AS PARTICIPANT_DATA_WITHHELD_UNTIL_LSLV_FLAG,
    TRIM(PARTICIPANT_ELIGIBLE_TO_RETURN_FLAG) AS PARTICIPANT_ELIGIBLE_TO_RETURN_FLAG,
    TRIM(DELETE_FLAG) AS DELETE_FLAG_SRT
  FROM srt_study
),

cv_transformed AS (
  SELECT
    TRIM(STUDY_ID) AS STUDY_ID,
    TRIM(STUDY_BUSINESS_RATIONALE_CATEGORY) AS BUSINESS_RATIONALE,
    TRIM(STUDY_MED_RESPONSIBILTY) AS MEDICAL_RESPONSIBILITY,
    TRIM(STUDY_PROJECT_PLAN_FINANCE_TYP) AS PROJECT_PLAN_TYPE,
    CAST(STUDY_SAP_FINISH_DATE AS TIMESTAMP) AS SAP_FINISH_DATE,
    STUDY_PCNT_COMP_SAP AS SAP_PCT_COMPLETED,
    CAST(STUDY_SAP_START_DATE AS TIMESTAMP) AS SAP_START_DATE,
    TRIM(STUDY_CPM) AS STUDY_CPM,
    TRIM(STUDY_EXECUTION_STATE) AS STUDY_EXECUTION_STATE,
    TRIM(STUDY_PERFORMING_SITE) AS STUDY_PERFORMING_SITE,
    TRIM(STUDY_PROJECT_PLAN_NAME) AS STUDY_PROJECT_PLAN_NAME,
    TRIM(STUDY_PROJECT_PLAN_TEMPLATE_NAME) AS STUDY_PROJECT_PLAN_TEMPLATE_NAME,
    TRIM(STUDY_STATUS_PLAN) AS STUDY_STATUS_PLAN
  FROM cv_study_data
),

portfolio_details AS (
  SELECT
    TRIM(STUDY_ID) AS STUDY_ID,
    TRIM(BUSINESS_GROUP) AS BUSINESS_GROUP,
    TRIM(CCS_CLINICAL_PLACEMENT) AS CCS_CLINICAL_PLACEMENT
  FROM dsopi_st_cln_study_portfolio
),

study_portfolio_overview AS (
  SELECT
    in0.MONITOR_VISIT_PLAN_INTERVAL_MAX AS MONITOR_VISIT_PLAN_INTERVAL_MAX
  FROM dsopi_transformed AS in0
  INNER JOIN srt_transformed AS in1 ON in0.STUDY_ID = in1.STUDY_ID
  INNER JOIN cv_transformed AS in2 ON COALESCE(in0.STUDY_ID, in1.STUDY_ID) = in2.STUDY_ID
  JOIN portfolio_details AS in3 ON COALESCE(in0.STUDY_ID, in1.STUDY_ID) = in3.STUDY_ID
)
SELECT MONITOR_VISIT_PLAN_INTERVAL_MAX FROM study_portfolio_overview
